export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

